In [1]:
import open3d as o3d
import numpy as np
import copy
import utils.alignment as al
import utils.filter as fltr

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
source = o3d.io.read_point_cloud(r'point_clouds/Coffee.ply')
source = fltr.filter_background(source)
target = copy.deepcopy(source)

In [3]:
# disturb source
trans_init = np.asarray([[0.0, 0.0, 1.0, 0.0], [1.0, 0.0, 0.0, 0.0],
                             [0.0, 1.0, 0.0, 0.0], [0.0, 0.0, 0.0, 1.0]])
source.transform(trans_init)

PointCloud with 17662 points.

In [18]:
transformation = al.global_registration(source, target)
source_temp = copy.deepcopy(source)
target_temp = copy.deepcopy(target)

transformation = transformation.copy()
transformation[0,3] = 0.001 # add a tiny bit of offset so we can see alignment otherwise they are perfectly overlapped
print(transformation)
source_temp.transform(transformation)
source_temp.paint_uniform_color([1, 0.706, 0])
target_temp.paint_uniform_color([0, 0.651, 0.929])
o3d.visualization.draw_geometries([source_temp, target_temp])

[[-5.55111512e-17  1.00000000e+00  1.11022302e-16  1.00000000e-03]
 [-1.11022302e-16  5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 1.00000000e+00  1.11022302e-16  0.00000000e+00 -2.54787511e-18]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[Open3D WARNING] GLFW Error: WGL: Failed to make context current: The handle is invalid. 
